#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom -b &
lxqt-policykit-agent &
feh --bg-fill ~/wallpaper --no-fehbg &
polybar --reload default &
greenclip daemon &

#check if udiskie is already running
udiskie_pid=$(pidof -w udiskie);
if [[ -z "$udiskie_pid" ]]; then
  udiskie -s &
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled


